version: "3.11"

services:

  shop:
    build:
      context: .
      dockerfile: docker/shop/Dockerfile
    image: shop:0.0.1-dev
    container_name: shop
    command: bash docker/runserver.sh
    environment:
      - DB_HOST=shop_db
      - DB_PORT=5432
    env_file:
      - config/.env/shop.env
    depends_on:
      - shop_db
    expose:
      - 8000
    networks:
      - shop_db_network
      - nginx_network
#    volumes:
#      - ./shop:/home/appuser/app

  warehouse:
    build:
      context: .
      dockerfile: docker/warehouse/Dockerfile
    image: warehouse:0.0.1-dev
    container_name: warehouse
    command: bash docker/runserver.sh
    environment:
      - DB_HOST=warehouse_db
      - DB_PORT=5432
    env_file:
      - config/.env/warehouse.env
    depends_on:
      - warehouse_db
    expose:
      - 8001
    networks:
      - warehouse_db_network
      - nginx_network
#    volumes:
#      - ./warehouse:/home/appuser/app

  shop_db:
    container_name: shop_db
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=shop_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - shop-db-data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - shop_db_network

  warehouse_db:
    container_name: warehouse_db
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=warehouse_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - warehouse-db-data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - warehouse_db_network

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    restart: on-failure
    networks:
      - nginx_network
    ports:
      - 80:80
      - 8001:8001
    depends_on:
      - shop
      - warehouse
    healthcheck:
      test: [ "CMD-SHELL", "ps ax", "|" ,"grep -v grep", "|" ,"grep nginx",  "||", "exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  shop_db_network:
  warehouse_db_network:
  nginx_network:

volumes:
  shop-db-data:
  warehouse-db-data: